### ISSUE TITLE
Can use the File Output in the Compositing to save the file?

### ISSUE THREAD

**Issue by chenpaner** [jeinselenVF/VF-BlenderAutosaveRender#2]
This plugin can only save the format files in the Output Panel , Can use the File Output in the Compositing to save the file?
I am now using another plugin that automatically names according to the rendering time. It can output multi-layer exr files, but its naming method is too simple and does not have the flexibility of your plugin. Can you combine the advantages of the two plugins?

Here is the link to that plugin：https://gist.github.com/robertguetzkow/8dacd4b565538d657b72efcaf0afe07e

**Comment by jeinselen** [comment]
I have good news for you! This feature was already added to the local version I've been using the past few months, it's just not documented and committed to Github yet. There is a key difference in how I've implemented the approach, however, and it comes with some limitations.

The plugin you've linked to fully overwrites the base path of all output file nodes in the compositor using a single source string. This could be made more dynamic by incorporating variable replacement, but all output nodes would use the same path (they're all overwritten indiscriminately), and updating the individual image output names would not be supported.

My approach dynamically replaces {variable} patterns in both base path and individual output names, supporting the same feature set as the animation output path (which is already an option for outputting layered EXR with dynamic names, just not very convenient for still images). The original variable strings are then restored after rendering completes to ensure dynamic changes are accurately implemented the next time you render (date, render engine, etcetera...everything is replaced dynamically at render time and restored afterward). The major limitation is that because the original variable strings are preserved in a simple internal value, it only updates a single node which must be named "File Output" (the default name for the first file output node added to the compositor). The work around for multiple output directories is to include those paths in the image file names, not the base path (which could be left as the project root).

![Screen Shot 2022-06-22 at 10 52 34 AM](https://user-images.githubusercontent.com/82116640/175062465-6ce0c724-fa81-4de2-a5cf-ba26d33c449f.png)

I'll try to get this posted soon so you can try it out and see if it works for you.

**Comment by chenpaner** [comment]
Thank you very much for making this plugin, the method in your reply is not very practical for me, because I have a lot of projects, I am looking forward to your new version of the plugin!

**Comment by jeinselen** [comment]
@chenpaner The latest version of VF Auto Save Render is available for download, featuring multiple feature updates along with compositing file output node support. Documentation lists the usage and limitations, hope you find it useful!

https://github.com/jeinselenVF/VF-BlenderAutoSaveRender/releases/tag/v1.7.3
