### ISSUE TITLE
Override path for existing .blend files

### ISSUE THREAD

**Issue by JPFlare** [jeinselenVF/VF-BlenderAutosaveRender#4]
One of the big benefits to me from this addon is the ability to save every render to one location without having to worry about it-- the problem is that I have TONS of older blend files where opening them defaults to the project folder for saving.

It would be ideal if there were a way to override the path to always be one location, so that any and all renders save their images there. I would much rather dig through a render folder for the image I need than dig through my entire file server looking for a particular image.

**Comment by jeinselen** [comment]
@JPFlare I've ended up changing way more of the plugin than I bargained for this past week, but I think this'll do the job! I'm working on a V2 release with UI refresh, revised feature sets, new variables (individual year, month, day, hour, minute, second variables), and other refinements. Should make it way easier to save files to dated folder structures and the like.

But most of all, there are now options to globally override the autosave file location, file name, and file format in the add-on preferences. Be warned that these values are saved with the add-on itself, and are not preserved when you disable/enable or install a new version of the add-on.

For example, if you're using the `{serial}` number variable, it'll reset to 0 every time the plugin is updated or is turned off and back on in the Blender Preferences. You can always use the default `project name + serial number` option (which searches the target folder for existing files before auto-generating a new serial number; should preventing overwriting) or something other than the `{serial}` number variable to differentiate files...but regardless, you'll need to manually preserve settings across plugin updates or when toggling the add-on status in preferences.

https://raw.githubusercontent.com/jeinselenVF/VF-BlenderAutoSaveRender/main/VF_autosaveRender.py

Uninstall the old plugin first, especially since there's a capitalisation change in the file name that will cause issues if not fully/correctly replaced in Blender.

Please let me know how this works for you, and if you come across any bugs. Thank you!

**Comment by JPFlare** [comment]
Hey, I gave it a shot but it's telling me to check the console for errors. I made sure to remove the old version first, I promise.

The console has a bunch of "key "VF_autosaveRender" not found'", if that helps with diagnostics any.

**Comment by JPFlare** [comment]
Nevermind, redownloaded it from the link after manually deleting every reference to the file I could find using Everything and it seems all good!

**Comment by jeinselen** [comment]
Yeah, it's my fault for deciding to "fix" the spelling (from Auto Save to Autosave), causing a cascade of alterations that ended up requiring a change in capitalisation of the file name. Non-Linux systems are generally case-insensitive by default, which causes issues when trying to update stuff like this. 😒

**Comment by jeinselen** [comment]
Override feature is included in the 2.x release — https://github.com/jeinselenVF/VF-BlenderAutosaveRender/releases/tag/v2.0.8
