### ISSUE TITLE
Additional compositor output nodes

### ISSUE THREAD

**Issue by Testone70** [jeinselenVF/VF-BlenderAutosaveRender#5]
Good morning John,
I am testing your VF-BlenderAutosaveRender and is pretty amazing. Is super stable and everything is working like a charm but I was wondering if there may be any cache to add additional compositor output nodes. Our blender pipeline is based on four compositor output nodes that render separate exr sequences for Beauty, Passes, Data and Cryptomatte. Right now artists should manually update all the output paths manually every-time they update the script to a new version which is highly risky as human errors may always occur. 
Hope to hear from you soon.
Best
Claudio Falconi
VFX supervisor ProximaMilano

**Comment by jeinselen** [comment]
Thanks for the feedback @Testone70! I'm so glad to hear it's been working well at your studio, save for the single file output node limitation. And good news; I finally had some time this evening to overhaul the node processing system. It should now support all file output nodes in the Compositing tab regardless of node name.

I haven't officially released version 2.0 yet (I try to use plugins for a while myself before publishing a new version), but you can download the latest here, which includes the all-nodes update:

https://raw.githubusercontent.com/jeinselenVF/VF-BlenderAutoSaveRender/main/VF_autosaveRender.py

If you have or had a previous version installed, make sure you fully uninstall it and reboot Blender first! The capitalisation of the plugin changed, and it'll give you a bunch of errors if it doesn't fully clear the old plugin before installing the new version (unless you're on a case sensitive Linux installation, that might not bug out!).

**Comment by jeinselen** [comment]
A very small word of caution; I seemed to find some particularly dumb mistakes after the initial 2.x refactoring the other month. While I think it's all fixed, I don't know if I _fully_ trust that I caught everything. You might treat it as beta software, though I've been successfully using 2.0.4 for the past month without issues.

If you absolutely must use version 1.9.2 but need to save multiple files, are you able to use multiple outputs in the first file output node? I've set up a bunch of different files and file types just using a single output node, and they don't have to be in the same directory either; you can include folder paths in the sub-path of each individual output instead of the global node path. Just an option, and I totally understand why that's not convenient or feasible for existing projects, multiple drive locations, or any number of other pipeline considerations. Which is why version 2.0.x should be a pretty major improvement. Hopefully it works just as reliably for you as previous releases!

If you don't mind, let me know your thoughts on version 2. Revised UI, new variables, etcetera.

**Comment by Testone70** [comment]
Ciao John,
thank you very much for the updated version. Just had a very first try of the new release. The compositor outputs are working, but in this first try I am experimenting one strange behavior. 
I am setting the render output like this:
<img width="618" alt="Screenshot 2023-03-10 at 00 15 10" src="https://user-images.githubusercontent.com/82100627/224181924-f53b56a6-052d-4a6c-9ee3-7bf402f02d4d.png">

and a couple of compositor output like that:
<img width="465" alt="Screenshot 2023-03-10 at 00 16 44" src="https://user-images.githubusercontent.com/82100627/224182139-f4f91240-a6af-43c0-9f6a-54f8c9c13bfe.png">

The rendering output are just correct, but the compositor output, for some reason is creating some extra folder (the name syntax of those folder is correct) with image sequences with an unexpected naming convention... 
<img width="659" alt="image" src="https://user-images.githubusercontent.com/82100627/224183353-3c7f8cb2-e742-434c-ae73-4aa32202ce9c.png">
The files in the pass folder have the same name of the files in the alpha folder.

I will go for more in depth tests.
Best
Claudio

**Comment by jeinselen** [comment]
Ciao Claudio,

Thanks for attaching screenshots, that helps diagnose the issue! It's because the file output node doesn't work like the file output in the render tab. The base path is a base path to a directory, not an image output. It's saving exactly as intended by Blender, creating the "...####..exr" path as a folder, and then saving the "image" output (plus frame number and extension) inside of that base path. I think what you're looking for is something like this:

![Screenshot 2023-03-09 at 6 57 13 PM](https://user-images.githubusercontent.com/82116640/224188354-02a2210d-6803-4317-bc45-ca9d5a80993a.png)

Whenever using a file output node, open the Node sidebar Properties panel to add and edit the individual image outputs. That's how you set the file output name. Note that each image output in the file output node can actually use unique file formats if needed, it's a pretty flexible system. Which is why Autosave Render didn't originally support more than file output node; unless you're outputting to entirely different directories, there's not usually a need for more than one file output node.

Cheers,
John

**Comment by Testone70** [comment]
Ciao John,
The thing is that apparently my UI is different from yours...
![image](https://user-images.githubusercontent.com/82100627/224336490-0d955f52-10e2-4b01-bedd-30af4329ceba.png)
I am testing on Blender 3.3.1. Any preferred version to be used on your side?
Best
Claudio

**Comment by jeinselen** [comment]
That's strange! The screenshot I posted was from Blender 3.4.1, but I'm seeing the same per-input settings in 3.3.4 and 2.9.11. Not sure what would account for the difference, and I didn't think platform would change node features available (I use MacOS). I also don't think the plugin should have any impact here; it only prepends UI to the node properties panel to add the variables popup button and serial number input, nothing else. Are you running a custom build of Blender?

**Comment by jeinselen** [comment]
Multi-node feature is included in the 2.x release — https://github.com/jeinselenVF/VF-BlenderAutosaveRender/releases/tag/v2.0.8
